algoritmo "Sistema de Login"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Ricardo Silva]
// Descrição   : Sistema de login
// Autor(a)    : Vinicius Eduardo
// Data atual  : 11 de Abril de 2026
var
//variáveis
teste: caractere

inicio
//desenvolvimento
teste <- "Este é um teste."
escreval ("Variável Teste")
escreva ("O valor da variável TESTE é: " + teste)

fimalgoritmo